name: Daily Script Runner


on: 
    schedule: 
      - cron: "0 10 * * *"
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Make script executable
              run: chmod +x weather.sh
            - name: Run weather.sh script
              run: ./weather.sh
            - name: Clone Repository
              run: |
                git clone https://github.com/deMachad0/computer_infrastructure.git cloned-repo
            